# Use a lightweight base image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Bundle app source
COPY . .

# Expose the port on which the app will run (modify if needed)
EXPOSE 3000

# Command to run your application in test
CMD ["npm", "run", "test"]
