apiVersion: v1
kind: Service
metadata:
  name: resume-site-testing
spec:
  selector:
    app: resume-site
    env: testing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

