apiVersion: v1
kind: Service
metadata:
  name: resume-site-dev
spec:
  selector:
    app: resume-site
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer 
