apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-site-prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: resume-site
      env: prod
  template:
    metadata:
      labels:
        app: resume-site
        env: prod
    spec:
      containers:
        - name: resume-site
          image: cappybara12/testing-deployment:prod
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: prod
