# Use a lightweight base image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install production dependencies only
RUN npm install --only=production

# Bundle app source
COPY . .

# Expose the port on which the app will run (modify if needed)
EXPOSE 3000

# Command to start your application in production
CMD ["npm", "start"]
